// <auto-generated />
namespace FakeApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Demo4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Demo4));
        
        string IMigrationMetadata.Id
        {
            get { return "202307271345599_Demo4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
