// <auto-generated />
namespace FakeApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Demo9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Demo9));
        
        string IMigrationMetadata.Id
        {
            get { return "202307311144328_Demo9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
